name: build branch ${GITHUB_REF#refs/heads/} commit $(git rev-parse --short "$GITHUB_SHA")

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - run: npm i
    - run: npm run build --if-present